language: cpp
os:
- linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.8-multilib
    - gcc-multilib
    - build-essential
    - libbluetooth-dev
    - libudev-dev
    - libusb-1.0-0-dev
env:
  global:
  - DEBUG_CORE_DUMP="true"
  matrix:
  - PACKAGER_NODE_VERSION="5.5" PACKAGER_ARCH="amd64" MAIN_BUILD="true"
  - PACKAGER_NODE_VERSION="5.5" PACKAGER_ARCH="386"
matrix:
  fast_finish: true
  exclude:
  - os: osx
    env: PACKAGER_NODE_VERSION="5.5" PACKAGER_ARCH="386"
branches:
  only:
  - "/^v[0-9]/"
before_install:
- ulimit -c unlimited -S
- PACKAGER_URL="https://meshblu-connector.octoblu.com/tools/packager/latest"
- curl -fsS "${PACKAGER_URL}/travis_install_node.sh" -o /tmp/travis_install_node.sh
- chmod +x /tmp/travis_install_node.sh
- ". /tmp/travis_install_node.sh"
- if [ "$TRAVIS_OS_NAME" == "linux" -a "$MAIN_BUILD" == "true" ]; then export NPM_PUBLISH="true"; fi
install:
- npm install --build-from-source
before_deploy:
- npm run generate:package
- npm run generate:schema
- cp schemas.json deploy
deploy:
- provider: releases
  api_key:
    secure: "T4Cor84QEDn0Qql+bNqL+VLcLieU/iZ5qf5jWzXc/mjTCOrho2qOEwOjrLUX5foUJZ8PEjXLPz+vjfLc33FSGl8hvaTYk29DwvVLe4mvtjbelmXkZuvRHYaRvjocxRE8IM8BCUDeJKImRhKp8C0l3HI66mR2t66J0lrkFopfgrCOjWbW7GC0rgx+d+whtcu8sHdUuCmYaJCVywZ0FLEr2VsIaWqOPbEI38dmUlq7ZbTOvFRfcZE9obgDgKZe0BPC86AqaRTPyalq30tYhXnx8FbNk3vdq9sW5QWtK3R/CxW1EIUez//Nf0ms0z3PGN3R6YLzi4Umx+SuqSME7RI99wJjFcRpMmJTrtaiR5e65K8O64aakPmXpd81sITzoAlusM9OwZ/0z5yidkW5XJ+Qo/fXDNv4Nfpj9lWc8DB5FBkkDNcVbtxr822dfAefW2bYNjvjt7iO0BGNdOsbnJuQtfksFIq2fGvQUgoIoxeASEju3lfHe4cFczjdxWuwm/gBIAaXOsMEd/lB91/O9s1cPyluDNtXPfq5zoxaCSmwGuq5+O31bkHStiUWKuxnGrteuXW6qTUUkL2PPaYQqDmgb5rT5LN/YeTVXJv4GauuxCUSRDPXtkEXJGwtTm5cii8K7EfRf7QkmR2zwabPrM3DUsLsYE/7mCI+JhoynhKUmKw="
  file_glob: true
  file:
  - "deploy/*"
  skip_cleanup: true
  on:
    tags: true
